version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_PATH=/data/database.sqlite
      - UPLOADS_DIR=/data/uploads
      # Set a strong secret in production:
      - JWT_SECRET=change-me-in-production
    volumes:
      - diet_tracker_data:/data
volumes:
  diet_tracker_data:


