services:
  - type: web
    name: diet-tracker
    env: docker
    plan: free
    repo: https://github.com/JulianJua/Diet-Tracker
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true


