services:
  - type: web
    name: diet-tracker
    env: node
    plan: starter
    repo: https://example.com/your/repo
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /data/database.sqlite
      - key: UPLOADS_DIR
        value: /data/uploads
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1


